import Head from 'next/head';
import { Header } from '@/components/header/Header';
import React, {Suspense} from 'react';
import '../components/translate/i18next';
import Person from '@/components/personPage/personName';
import FilmList from '@/components/filmList';



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />    
      </Head>
      <Suspense fallback={<div>Loading...</div>}>
      <main>
        <Header />

        
        <Person />
      </main>
      </Suspense>
    </>
  )
}
